[package]
name = "todo-tui"
version = "0.1.0"
edition = "2021"

[dependencies]
tui = { package = "ratatui", version = "0.22.0", features = ["all-widgets", "crossterm"]}
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
crossterm = "0.27"
todo-txt = "3.1"
toml = "0.7"
enum_dispatch = "0.3"
chrono = "0.4"
log4rs = "1.2"
notify = "6.0"
tui-input = { version = "0.8", features = ["crossterm"], default-features = false }
regex = { version = "1.3", default-features = false, features = ["std"] }

[dev-dependencies]
test-log = "0.2.13"
env_logger = "0.10.0"
