active_color = "Blue"
init_widget = "List"
window_title = "ToDo tui"
todo_path = "/home/jirka/todo.txt"
archive_path = "/home/jirka/archive.txt"
wrap_preview = true
log_file = "log.log"
log_level = "TRACE"
file_watcher = true
list_shift = 4
pending_sort = "Priority"
done_sort = "None"
preview_format = """
Pending: $pending Done: $done
Subject: $subject
Priority: $priority
Create date: $create_date
Link: $link"""
layout = """
[
    Direction: Horizontal,
    Size: 50%,
    List: 50%,
    [ Direction: Vertical,
      Done: 30%,
      [ 
        Size: 30%,
        Contexts,
        Projects,
      ],
      Preview: 40%,
    ],
]
"""

[category_color]
bg = "Blue"

[list_active_color]
bg = "LightRed"

[pending_active_color]

[done_active_color]

[autosave_duration]
secs = 30
nanos = 0

[list_refresh_rate]
secs = 5
nanos = 0

[category_style]
fg = "LightBlue"

[projects_style]

[contexts_style]

[hashtags_style]

[custom_category_style."+todo-tui"]
fg = "LightRed"

